SET NAMES utf8;
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

INSERT INTO `comments` (`id`, `user_id`, `text`) VALUES
  (1, 10, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy'),
  (2, 10, 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio'),
  (3, 75, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque'),
  (4, 42, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat'),
  (5, 16, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam'),
  (6, 36, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc'),
  (7, 65, 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh'),
  (8, 32, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis'),
  (9, 9, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla'),
  (10, 9, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum'),
  (11, 5, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor'),
  (12, 2, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis'),
  (13, 18, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec'),
  (14, 64, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac'),
  (15, 70, 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit'),
  (16, 59, 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
  (17, 70, 'phasellus in felis donec semper sapien a libero nam dui proin'),
  (18, 30, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate'),
  (19, 64, 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet'),
  (20, 3, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id'),
  (21, 58, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum'),
  (22, 76, 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in'),
  (23, 30, 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu'),
  (24, 92, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla'),
  (25, 66, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse'),
  (26, 14, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum'),
  (27, 75, 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum'),
  (28, 82, 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis'),
  (29, 95, 'vel sem sed sagittis nam congue risus semper porta volutpat quam'),
  (30, 8, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec'),
  (31, 78, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc'),
  (32, 79, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede'),
  (33, 57, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien'),
  (34, 32, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus'),
  (35, 86, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis'),
  (36, 50, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue'),
  (37, 7, 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis'),
  (38, 91, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus'),
  (39, 65, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula'),
  (40, 49, 'aenean sit amet justo morbi ut odio cras mi pede'),
  (41, 12, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue'),
  (42, 43, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel'),
  (43, 3, 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede'),
  (44, 90, 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac'),
  (45, 96, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum'),
  (46, 92, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam'),
  (47, 83, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede'),
  (48, 31, 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla'),
  (49, 26, 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus'),
  (50, 13, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae'),
  (51, 2, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien'),
  (52, 99, 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra'),
  (53, 6, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis'),
  (54, 60, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc'),
  (55, 23, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non'),
  (56, 42, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis'),
  (57, 79, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut'),
  (58, 75, 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum'),
  (59, 17, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede'),
  (60, 93, 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus'),
  (61, 87, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec'),
  (62, 75, 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros'),
  (63, 89, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus'),
  (64, 64, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in'),
  (65, 20, 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque'),
  (66, 83, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida'),
  (67, 35, 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet'),
  (68, 95, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit'),
  (69, 47, 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst'),
  (70, 68, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit'),
  (71, 15, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla'),
  (72, 29, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean'),
  (73, 85, 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus'),
  (74, 68, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing'),
  (75, 83, 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna'),
  (76, 12, 'lacinia aenean sit amet justo morbi ut odio cras mi pede'),
  (77, 35, 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy'),
  (78, 22, 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris'),
  (79, 19, 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse'),
  (80, 55, 'in sagittis dui vel nisl duis ac nibh fusce lacus purus'),
  (81, 76, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat'),
  (82, 18, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo'),
  (83, 99, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet'),
  (84, 29, 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum'),
  (85, 74, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in'),
  (86, 33, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id'),
  (87, 91, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus'),
  (88, 87, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget'),
  (89, 72, 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend'),
  (90, 91, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus'),
  (91, 39, 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis'),
  (92, 77,
   'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque'),
  (93, 53,
   'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero'),
  (94, 24, 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing'),
  (95, 97, 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget'),
  (96, 65,
   'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus'),
  (97, 59,
   'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet'),
  (98, 79, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum'),
  (99, 96, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus'),
  (100, 81,
   'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit');
